<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Initially developped for :
 * Université de Cergy-Pontoise
 * 33, boulevard du Port
 * 95011 Cergy-Pontoise cedex
 * FRANCE
 *
 * Book usernames for creation
 *
 * @package   tool_loginreservation
 * @copyright 2018 Laurent Guillet <laurent.guillet@u-cergy.fr>
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 *
 * File : en/tool_loginreservation.php
 * English language file
 */
 
$string['pluginname'] = 'Login reservation';
$string['student'] = 'Student';
$string['teacher'] = 'Teacher';
$string['usertype'] = 'User type';
$string['numusers'] = 'Number of users';
$string['title'] = 'Create external logins';
$string['formintro'] = 'This program does not create any login, it gives you available username that you can use when you create accounts.<br><br>'
	.'Please use them quickly and do not ask for too many.';
$string['returnlink'] = '<a href=\'index.php\'>Go back to login creation page</a><br><br>';
$string['logincreated'] = 'Login(s) created';
$string['type'] = 'Type';
$string['generatedby'] = 'Generated by';
$string['generatedon'] = 'Generated on';
$string['usercreated'] = 'User created';
$string['notused'] = 'Not used';
$string['previouslogins'] = '<a href=\'index.php?previous=1\'>List of logins previously created</a>';
$string['privacy:metadata'] = 'The tool only stores administrators data.';

